# Generated by Django 4.2 on 2023-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=100)),
                ('subject', models.ManyToManyField(to='queries.subject')),
            ],
        ),
    ]
