# Generated by Django 4.2 on 2023-04-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], default='blackwhite', max_length=100),
        ),
    ]
