# Generated by Django 4.2 on 2023-04-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_room_student_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentONE',
            fields=[
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.course')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.room')),
            ],
        ),
    ]
