# Generated by Django 4.2 on 2023-04-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_studentone_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentone',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='studentone',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentone',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
