# Generated by Django 4.2 on 2023-04-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_studentone_id_studentone_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_no',
        ),
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
