# Generated by Django 4.2 on 2023-04-30 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_room_id_room_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='studentONE',
        ),
    ]
