# Generated by Django 4.2 on 2023-04-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
