# Generated by Django 4.2.4 on 2023-08-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_passby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
