# Generated by Django 4.2.4 on 2023-09-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active',
            new_name='is_admin',
        ),
    ]
