version: '3.1'

services:

  db:
    image: mysql
    ports: 
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_USERNAME: mysql_db
      MYSQL_ROOT_NAME: mysql_db
      
