# Generated by Django 4.2.4 on 2023-08-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualise', '0004_alter_details_added_alter_details_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='added',
            field=models.DateTimeField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='country',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='end_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='impact',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='insight',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='pestle',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='published',
            field=models.DateTimeField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='region',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='relevance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='sector',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='source',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='start_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='topic',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
