# Generated by Django 4.2.4 on 2023-08-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualise', '0005_alter_details_added_alter_details_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='added',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='details',
            name='published',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
