# Generated by Django 4.2.4 on 2023-08-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualise', '0009_alter_details_added_alter_details_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='end_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='intensity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='likelihood',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='relevance',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='start_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
