# Generated by Django 4.2.4 on 2023-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualise', '0010_alter_details_end_year_alter_details_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
