# Generated by Django 4.2.4 on 2023-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualise', '0012_alter_details_added_alter_details_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='added',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='published',
            field=models.TextField(blank=True, null=True),
        ),
    ]
