# Generated by Django 4.2 on 2023-04-13 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 13, 22, 37, 35, 604345))),
            ],
        ),
    ]
